<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- parent 标签指的是在maven工程中的父工程
            springboot项目都是Springboot的子工程
       -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.2</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <!-- 当前项目的坐标   -->
    <!-- 公司或者组织域名倒过来写   -->
    <groupId>com.gec</groupId>
    <!-- 项目模块的名称   -->
    <artifactId>springboot-demo</artifactId>
    <!-- 版本号   -->
    <version>0.0.1-SNAPSHOT</version>

    <!--  项目的名称  -->
    <name>springboot-demo</name>
    <!--  项目的描述  -->
    <description>springboot-demo</description>

    <!--  存放当前xml可能用到的参数  -->
    <properties>
        <java.version>17</java.version>
        <!--  统一管理langchain4j的版本      -->
        <langchain4j.verion>1.0.0-beta1</langchain4j.verion>
    </properties>

    <!-- 重点 ：存放坐标的 需要引入什么jar包就在这里写上对应jar包的坐标  -->
    <dependencies>

        <!-- springboot整合web模块的坐标       -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- springboot整合test单元测试的坐标       -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>


        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j</artifactId>
            <!-- 统一控制版本${langchain4j.verion} 使用变量的写法           -->
            <version>${langchain4j.verion}</version>
        </dependency>

        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-open-ai</artifactId>
            <version>${langchain4j.verion}</version>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-open-ai-spring-boot-starter</artifactId>
            <version>${langchain4j.verion}</version>
        </dependency>
        <!-- Springboot整合阿里通义千问       -->
                <dependency>
                    <groupId>dev.langchain4j</groupId>
                    <artifactId>langchain4j-community-dashscope-spring-boot-starter</artifactId>
                    <version>1.0.0-alpha1</version>
                </dependency>


<!--        图生文-->

        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-community-dashscope</artifactId>
            <version>1.0.0-alpha1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

        <!-- MyBatis Plus -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.5</version>
        </dependency>

        <!-- MySQL Driver -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.28</version>
        </dependency>



    </dependencies>

    <!-- 构建项目的一些插件   -->
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>